/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUARE_H_RPCGEN
#define _SQUARE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct square_in {
	long arg1;
};
typedef struct square_in square_in;

struct square_out {
	long res1;
};
typedef struct square_out square_out;

struct foodata {
	struct {
		u_int buffer_len;
		u_int *buffer_val;
	} buffer;
};
typedef struct foodata foodata;

#define SQUARE_PROG 202020
#define SQUARE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SQUAREPROC 1
extern  square_out * squareproc_1(square_in *, CLIENT *);
extern  square_out * squareproc_1_svc(square_in *, struct svc_req *);
#define ERRNOPROG 2
extern  void * errnoprog_1(void *, CLIENT *);
extern  void * errnoprog_1_svc(void *, struct svc_req *);
#define ERRPROGVERS 3
extern  void * errprogvers_1(void *, CLIENT *);
extern  void * errprogvers_1_svc(void *, struct svc_req *);
#define ERRNOPROC 4
extern  void * errnoproc_1(void *, CLIENT *);
extern  void * errnoproc_1_svc(void *, struct svc_req *);
#define ERRDECODE 5
extern  void * errdecode_1(void *, CLIENT *);
extern  void * errdecode_1_svc(void *, struct svc_req *);
#define ERRSYSTEMERR 6
extern  void * errsystemerr_1(void *, CLIENT *);
extern  void * errsystemerr_1_svc(void *, struct svc_req *);
#define ERRWEAKAUTH 7
extern  void * errweakauth_1(void *, CLIENT *);
extern  void * errweakauth_1_svc(void *, struct svc_req *);
#define SINKPROC 10
extern  void * sinkproc_1(foodata *, CLIENT *);
extern  void * sinkproc_1_svc(foodata *, struct svc_req *);
#define SUMPROC 11
extern  u_int * sumproc_1(foodata *, CLIENT *);
extern  u_int * sumproc_1_svc(foodata *, struct svc_req *);
extern int square_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SQUAREPROC 1
extern  square_out * squareproc_1();
extern  square_out * squareproc_1_svc();
#define ERRNOPROG 2
extern  void * errnoprog_1();
extern  void * errnoprog_1_svc();
#define ERRPROGVERS 3
extern  void * errprogvers_1();
extern  void * errprogvers_1_svc();
#define ERRNOPROC 4
extern  void * errnoproc_1();
extern  void * errnoproc_1_svc();
#define ERRDECODE 5
extern  void * errdecode_1();
extern  void * errdecode_1_svc();
#define ERRSYSTEMERR 6
extern  void * errsystemerr_1();
extern  void * errsystemerr_1_svc();
#define ERRWEAKAUTH 7
extern  void * errweakauth_1();
extern  void * errweakauth_1_svc();
#define SINKPROC 10
extern  void * sinkproc_1();
extern  void * sinkproc_1_svc();
#define SUMPROC 11
extern  u_int * sumproc_1();
extern  u_int * sumproc_1_svc();
extern int square_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_square_in (XDR *, square_in*);
extern  bool_t xdr_square_out (XDR *, square_out*);
extern  bool_t xdr_foodata (XDR *, foodata*);

#else /* K&R C */
extern bool_t xdr_square_in ();
extern bool_t xdr_square_out ();
extern bool_t xdr_foodata ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUARE_H_RPCGEN */
